blockchain_metal_client/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('blockchain_web_app/', include('blockchain_web_app.urls')),
    path('', RedirectView.as_view(url='/blockchain_web_app/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

blockchain_web_app/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('templates/', views.TemplateListView.as_view(), name='templates'),
    path('companies/', views.CompanyListView.as_view(), name='companies'),
    path('sign/', views.sign_template, name='template_sign'),
    path('recall/', views.recall_contract, name='template_recall'),
    path('profile/', views.watch_profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('template/<int:pk>', views.TemplateDetailView.as_view(), name='template-detail'),
    path('template/<int:pk>/delete/', views.TemplateDelete.as_view(), name='template_delete'),
    path('template/create/', views.create_template, name='template_create'),
    path('company/<int:pk>', views.CompanyDetailView.as_view(), name='company-detail'),
    path('company/<int:pk>/delete/', views.CompanyDelete.as_view(), name='company_delete'),
    path('company/create/', views.CompanyCreateView.as_view(), name='company_create'),
]

blockchain_web_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user_id=models.OneToOneField(User, on_delete=models.CASCADE)
    job = models.CharField(max_length=200, default="Сотрудник")
    patronymic = models.CharField(max_length=200, default="Ивановна")
    signature_image = models.ImageField(upload_to='sign_image/%Y/%m/%d', blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user_id=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return '{0} {1} {2} ({3})'.format(self.user_id.last_name,self.user_id.first_name,self.patronymic, self.job)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


# class Countries(models.Model):
#     country = models.CharField(max_length=200, default="Россия")
#
#
# class UnitsOfMeasurement(models.Model):
#     unit_of_measurement = models.CharField(max_length=10, default="кг")
#
#
# class Products(models.Model):
#     name = models.CharField(max_length=200, default="ПPOBOЛOKA.AЛ CПЛ AK5.CBAPOЧHAЯ.D1")
#     country = models.ForeignKey(Countries, on_delete=models.CASCADE)
#     unit_price = models.FloatField(default=0)
#     unit_of_measurement = models.ForeignKey(UnitsOfMeasurement, on_delete=models.CASCADE)

class Company(models.Model):
    title = models.CharField(max_length=200, default='ООО "Наименование"')
    phone = models.CharField(max_length=50, default='+7(999) 999-99-99')
    name = models.CharField(max_length=200, default='Иванов И.И.')
    inn = models.CharField(max_length=12, default='999999999999')
    ogrn = models.CharField(max_length=15, default='999999999999999')
    address = models.CharField(max_length=200, default='999999, Челябинская обл, г.Челябинск, ул.Ленина, дом № 9, квартира 9')
    mail_address = models.CharField(max_length=200, default='999999, Челябинская обл, г.Челябинск, ул.Ленина, дом № 9, квартира 9')
    email = models.CharField(max_length=100, default='email@mail.com')
    created_data = models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')

    def __str__(self):
        return '{0} ({1})'.format(self.title, self.created_data)

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'
        ordering = ['-created_data']


class ContractTemplate(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    buyer = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='buyer')
    supplier = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='supplier')
    json_file = models.FileField(upload_to='json/', blank=True)
    created_data = models.DateTimeField(auto_now_add=True, verbose_name='Создан')

    def __str__(self):
        return '{0} - {1} ({2})'.format(self.buyer.title, self.supplier.title, self.created_data)

    class Meta:
        verbose_name = 'Шаблон договора'
        verbose_name_plural = 'Шаблоны договоров'
        ordering = ['-created_data']

blockchain_web_app/forms.py
from django import forms
from .models import Company, ContractTemplate


class TemplateRecallForm(forms.Form):
    diplom_file = forms.FileField(required=True, label="", widget=forms.FileInput(
        attrs={'style': 'display: none;', 'accept': 'application/json'}))


class ContractTemplateCreateForm(forms.Form):
    buyer = forms.ModelChoiceField(required=True, widget=forms.Select(attrs={'class': 'myfield'}),
                                   queryset=Company.objects.all(), label="Покупатель")
    supplier = forms.ModelChoiceField(required=True, widget=forms.Select(attrs={'class': 'myfield'}),
                                      queryset=Company.objects.all(), label="Поставщик")


class ContractTemplateSignForm(forms.Form):
    user_template = forms.ModelChoiceField(required=True, widget=forms.Select(attrs={'class': 'myfield'}),
                                           queryset=ContractTemplate.objects.all(), label="Шаблон договора")
    roster = forms.FileField(required=True, label="",
                             widget=forms.FileInput(attrs={'style': 'display: none;', 'accept': '.csv'}))

    def __init__(self, temp_user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_template'].queryset = ContractTemplate.objects.filter(user_id__exact=temp_user.id)

blockchain_web_app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, DeleteView, CreateView

from blockchain_web_app.forms import ContractTemplateCreateForm, ContractTemplateSignForm, TemplateRecallForm
from blockchain_web_app.models import ContractTemplate, Company
from blockchain_web_app.utils.create_and_save_template_to_bd import create_and_save_template_to_bd
from handle_files import handle_upload_json
from blockchain_web_app.utils.process_file_signature import process_file_signature
from pdiplom.issuer_diplom import connection_rpc_on, broadcast_tx
from vcontract.json_formatter import get_formatted_verification_info
from vcontract.verifier import verify


def index(request):
    if request.method == 'POST':
        if not connection_rpc_on():
            error = 'Нет связи с сервером'
            return render(
                request,
                'info_page.html',
                {'message': error}
            )
        file = request.FILES['filesjson']
        json_byte_file = file.read()
        json_file = json_byte_file.decode()

        m1, m2 = verify(json_file)
        if m1 == 'exist' and m2 == 'same':
            verification_result = 1
        elif m1 == 'recalled':
            verification_result = 2
        else:
            verification_result = 0

        info = get_formatted_verification_info(json_file, verification_result)
        return render(
            request,
            'award.html',
            info
        )
    return render(
        request,
        'index.html'
    )


@login_required
def create_template(request):
    if request.method == 'POST':
        form = ContractTemplateCreateForm(request.POST, request.FILES)
        if form.is_valid():
            create_and_save_template_to_bd(form, request)
            return HttpResponseRedirect(reverse('templates'))
    else:
        form = ContractTemplateCreateForm()
    return render(
        request,
        'create_template.html',
        {'form': form}
    )


@login_required
def sign_template(request):
    if request.method == 'POST':
        form = ContractTemplateSignForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            if not connection_rpc_on():
                error = 'Нет связи с сервером'
                return render(
                    request,
                    'info_page.html',
                    {'message': error}
                )
            return process_file_signature(request)
    else:
        form = ContractTemplateSignForm(request.user)
    return render(
        request,
        'sign_template.html',
        {'form': form}
    )


@login_required
def recall_contract(request):
    if request.method == 'POST':
        form = TemplateRecallForm(request.POST, request.FILES)
        if form.is_valid():
            if not connection_rpc_on():
                error = 'Нет связи с сервером'
                return render(
                    request,
                    'info_page.html',
                    {'message': error}
                )
            contract = handle_upload_json(request.FILES['diplom_file'])
            contract_id = contract['id'].replace(PREFIX_UID, "")
            result, error = broadcast_tx(contract_id, 'deleted')
            if error:
                printed_res = result
            else:
                printed_res = 'Крнтракт успешно отозван'
            return render(
                request,
                'info_page.html',
                {'message': printed_res}
            )
    else:
        form = TemplateRecallForm()
    return render(
        request,
        'recall_diplom.html',
        {'form': form}
    )


@login_required
def watch_profile(request):
    user = request.user
    return render(
        request,
        'profile.html',
        {'user': user}
    )


class TemplateListView(LoginRequiredMixin, ListView):
    """Generic class-based view for a list of templates."""
    model = ContractTemplate

    def get_queryset(self):
        return ContractTemplate.objects.filter(user_id=self.request.user)


class TemplateDetailView(LoginRequiredMixin, DetailView):
    """Generic class-based detail view for a template."""
    model = ContractTemplate


class TemplateDelete(LoginRequiredMixin, DeleteView):
    model = ContractTemplate
    success_url = reverse_lazy('templates')


class CompanyCreateView(LoginRequiredMixin, CreateView):
    """Generic class-based view for a list of templates."""
    model = Company
    fields = '__all__'
    success_url = reverse_lazy('companies')



class CompanyListView(LoginRequiredMixin, ListView):
    """Generic class-based view for a list of templates."""
    model = Company


class CompanyDetailView(LoginRequiredMixin, DetailView):
    """Generic class-based detail view for a template."""
    model = Company


class CompanyDelete(LoginRequiredMixin, DeleteView):
    model = Company
    success_url = reverse_lazy('companies')

blockchain_web_app/templates/award.html
{% extends 'base_generic.html' %}

{% block content %}

    <!-- Award -->
    {% block award %}
<!--        <div class="issuer-logo">-->
<!--            <img src="{{ logoImg }}" alt="Logo"/>-->
<!--        </div>-->
<!--        <div class="certificate-owner">-->
<!--            <h1>{{ name }}</h1>-->
<!--        </div>-->

        <div class="certificate-meta">
            <span class="certificate-name"> Покупатель: {{ buyer }}</span>
            <span class="certificate-name">Поставщик: {{ supplier }}</span>
<!--            <span class="issuer-name">{{ organization }}</span>-->

        </div>

        <table class="table">
            <thead>
                <tr>
                    <th>Наименование товара</th>
                    <th>Ед. изм</th>
                    <th>Кол–во товара</th>
                    <th>Цена за единицу в руб., без  НДС </th>
                    <th>Страна происхождения товара</th>
                </tr>
            </thead>
            <tbody>
                {% for item in specification%}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{item.unit_of_measurement}}</td>
                    <td>{{ item.amount }}</td>
                    <td>{{ item.unit_price }}</td>
                    <td>{{ item.country }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="certificate-description">
<!--            <p>{{ text }}</p>-->
            <p class="date-span">Подписан: {{ issued_on }}</p>
        </div>
        <div class="sinature">
            <p style="display: inline;">Подписал: {{ responsible_job }} {{responsible_name}} </p>
            <img src="{{ signature_img }}" id="signature-img" alt="Signature" style="width: 20%;height:20%;float: right;"/>
        </div>



    {% endblock %}
<!--    <div class="certificate-signature">-->

<!--        <p>{{ organization }} подписал в цифровом виде диплом и выпустил его в блокчейне <span class="chain">{{ award.chain }}.</span></p>-->
<!--                <img src="{{ sealImg }}" id="seal-img" alt="Seal" style="max-width: 34%;-->
<!--    float: right;"/>-->

<!--    </div>-->
    <div class="verify">

        <button id="verify-button" value="{{ verification_info }}" class="buv-c-verify-button_award">Проверить договор</button>
        {% if verification_result == 1 %}
        <p class="verified"><img id="verified-icon" src="/static/img/verified.png" style="max-width: 36px;max-height: 36px;"> договор существует в блокчейне</p>
        {% elif verification_result == 2 %}
        <p class="not-verified"><img id="recall-icon"
                                                          src="/static/img/not-verified.png" style="max-width: 36px;max-height: 36px;"> договор отозван </p>
        {% else %}
        <p class="not-verified"><img id="not-verified-icon"
                                                          src="/static/img/not-verified.png" style="max-width: 36px;max-height: 36px;"> договор не существует в блокчейне </p>
        {% endif %}
    </div>





<!--    <div class="issuer-id">-->
<!--        <strong>Сайт:</strong> <span class="issuer-id-url"><a style="cursor: pointer;text-decoration: none;color: inherit;font-size: 18px;" href="{{ url }}" target="_blank">{{ url }}</a></span>-->
<!--        <strong>Почта:</strong> <span class="issuer-id-url"><a style="cursor: pointer;text-decoration: none;color: inherit;font-size: 18px;" href="{{ email }}" target="_blank">{{ email }}</a></span>-->
<!--    </div>-->

    <a href="{% url 'index' %}" class="back-button">Проверить другой договор</a>
{% endblock %}

blockchain_web_app/templates/base_generic.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8">
	{% block title %}<title>BlockProject</title>{% endblock %}
	<link href="https://fonts.googleapis.com/css?family=Forum|Scada" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Merriweather&family=Playfair+Display&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="/static/css/index.css">

</head>
<body>
	<div class="content_page">
		<div class="header">
			<div class="header_container">
				<div class="header_left">
					<span class="logo">BLOCKCHAIN</span>
				</div>
					<nav class="main-nav">
						<ul>
							<li class="menu_item"><a class="cd-signin" href="{% url 'index' %}">ГЛАВНАЯ</a></li>
							{% if user.is_authenticated %}
							<li class="menu_item"><a class="cd-signin" href="{% url 'profile'%}">ПРОФИЛЬ</a></li>
							<li class="menu_item"><a class="cd-signin" href="{% url 'companies'%}">КОМПАНИИ</a></li>
							<li class="menu_item"><a class="cd-signin" href="{% url 'templates'%}">ШАБЛОНЫ</a></li>
							<li class="menu_item"><a class="cd-signin" href="{% url 'template_sign'%}">ПОДПИСАТЬ</a></li>
<!--							<li class="menu_item"><a class="cd-signin" href="{% url 'template_recall'%}">ОТОЗВАТЬ</a></li>-->
							{% endif %}
							{% if user.is_authenticated %}
							<li class="menu_item"><a class="cd-signin" href="{% url 'logout'%}">ВЫХОД</a></li>
							{% else %}
							<li class="menu_item"><a class="cd-signin" href="{% url 'login'%}?next={{request.path}}">ВХОД</a></li>
							{% endif %}
						</ul>
					</nav>

			</div>
		</div>
		<div class="content">
			<div class="row">
				{% block content %}

				{% endblock %}
			</div>
		</div>
	</div>


	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript">
                                $('input').on('change', function() {

                                    var splittedFakePath = this.value.split('\\');
                                    $('#namefile').text(splittedFakePath[splittedFakePath.length - 1]);
                                    if (this.value!=null) {
                                        document.getElementById("verify2").type = 'sumbit';


                                    }
                                });
                                $('#verify2').click(function () {

                                        $('#namefile').text('Прикрепите файл');

                                })
        window.onload=function(){
            document.getElementById("verify-button").click();};

                            </script>

<script  src="/static/js/verification.js"></script>
    <script src="/static/js/footer.js"></script>

</body>
</html>

blockchain_web_app/templates/create_template.html
{%extends 'base_generic.html' %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data" style="display: flex; justify-content: center;flex-direction: column;margin-button: 20px;">
        {% csrf_token %}
        <table style="margin-bottom: 20px;">
        {{ form.as_table }}
        </table>
        <div class="buttons">
            <a  class="buv-c-back-button" href="{% url 'templates'%}" >Назад</a>
            <input class="buv-c-sumbit-button" type="submit"  value="Создать" style="margin-left: 20px;"/>
        </div>
    </form>

{% endblock %}

blockchain_web_app/templates/index.html
{%extends 'base_generic.html' %}

{% block content %}
    <form method="post" enctype=multipart/form-data action="{% url 'index' %}">
		{% csrf_token %}
        <div class="verifier">
		    <section class="buv-c-verifier-main">
			    <div class="buv-c-verifier-layout">
                    <div class="buv-c-footer-content">
                        <footer class="buv-c-footer">
                            <label for="buv-json-file-upload" class="buv-o-link buv-o-text-12">
						     <span class="buv-o-link__text--underline">Прикрепить JSON файл</span>
						    <input type=file name=filesjson accept="application/json" id="buv-json-file-upload" class="buv-u-visually-hidden">
                            </label>
				        </footer>
                        <div class="buv-c-footer" style="background-color: white">
                            <span id="namefile"></span>
                            {%if 'file_null_error' %}

                            {%endif%}
                        </div>
                    </div>

				    <section class>
					    <buv-certificate-input>
						    <section class="buv-c-certificate-input">

        					    <buv-verify-button>
        						    <button type="button" id="verify2" class="buv-c-verify-button">
        							    <span class="buv-c-verify-button__label">Проверить</span>

        						    </button>
        					    </buv-verify-button>
    					    </section>
					    </buv-certificate-input>
				    </section>

			    </div>
		    </section>
	    </div>

        <div>

        </div>
    </form>
				
{% endblock %}

blockchain_web_app/templates/info_page.html
{%extends 'base_generic.html' %}

{% block content %}
    <span class="issuer-name">{{ message }}</span>


    <a  class="buv-c-centerce-button" href="{% url 'index'%}" >На главную</a>

{% endblock %}

blockchain_web_app/templates/profile.html
{%extends 'base_generic.html' %}

{% block content %}
 <h2>Профиль пользователя: {{user.username}}</h2>
        <table>
        <tbody>
        <tr>
            <th>
                <label >Имя:</label>
            </th>
            <td>
                <span >{{ user.first_name }}</span>
            </td>
        </tr>
        <tr>
            <th>
                <label >Фамилия:</label>
            </th>
            <td>
                <span >{{ user.last_name}}</span>
            </td>
        </tr>
        <tr>
            <th>
                <label >Отчество:</label>
            </th>
            <td>
                <span >{{ user.profile.patronymic}}</span>
            </td>
        </tr>
        <tr>
            <th>
                <label >Должность:</label>
            </th>
            <td>
                <span >{{ user.profile.job}}</span>
            </td>
        </tr>
        <tr>
            <th>
                <label >Подпись:</label>
            </th>
            <td>
                <img src="{{ user.profile.signature_image.url}}" style="height: 100px;width: 100px;"></td>
        </tr>
        </tbody>
        </table>
    <a  class="buv-c-back-button" href="{% url 'index'%}" >Назад</a>
{% endblock %}

blockchain_web_app/templates/recall_diplom.html
{%extends 'base_generic.html' %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <label for="id_diplom_file" class="labelclass">Выбрать файл диплома для отзыва:</label>
    <table>
    {{ form.as_table }}

    </table>

        <span id="namefile" style="text-align: center; display: inherit; height: 20px; font-size: 20px;">Файл не выбран</span>


    <input class="buv-c-sumbit-button"  type="submit" value="Отозвать">
  </form>
    <a class="buv-c-back-button" href="{% url 'index'%}">Назад</a>
{% endblock %}

blockchain_web_app/templates/sign_template.html
{%extends 'base_generic.html' %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <label for="id_roster" class="labelclass">Выбрать файл со списком:</label>
        <span id="namefile" style="height: 20px; font-size: 18px;">Файл не выбран</span>
    <table>
    {{ form.as_table }}
    </table>
    <input class="buv-c-sumbit-button" type="submit" value="Опубликовать">
  </form>
<a class="buv-c-back-button" href="{% url 'index'%}">Назад</a>
{% endblock %}